require 'rubygems'
require 'bundler/setup'
require_relative 'parse_schedule'
require_relative 'parse_teachers'

DATA_DIRECTORY = "data"
RAW_SCHEDULE = "#{DATA_DIRECTORY}/converted.txt"
RAW_TEACHERS = "#{DATA_DIRECTORY}/export_faculty_schedules_wdaily_classes.csv"

directory LOG_DIRECTORY
directory DB_DIRECTORY

namespace :schedule do

  desc "For debug, parse raw schedule data."
  task :parse do
    h = hash_schedule RAW_SCHEDULE
    f = h.first
    p f
  end

  desc "Clean and load raw schedule data into database."
  task :load do
    h = hash_schedule RAW_SCHEDULE
    load_bell_schedules_from h
  end

  desc "Export schedule database to JSON file."
  task :output_json do
    write_schedule_to_json
  end

end

namespace :teacher do

  desc "For debug, parse raw teacher data."
  task :parse do
    h = hash_teachers RAW_TEACHERS
    f = h.first
    p f
  end

  desc "Clean and load raw teacher data into database."
  task :load do
    h = hash_teachers RAW_TEACHERS
    load_teachers_from h
  end

  desc "Export teacher database to JSON file."
  task :output_json do
    write_teachers_to_json
  end

  desc "Export teacher database to XLS, tabbed-delimited CSV."
  task :output_xls do
    write_teachers_to_xls
  end

end