require 'rubygems'
require 'bundler/setup'
require_relative 'parse_schedule'

DATA_DIRECTORY = "data"
RAW_SCHEDULE = "#{DATA_DIRECTORY}/converted.txt"

directory LOG_DIRECTORY
directory DB_DIRECTORY

namespace :schedule do

  desc "For debug, parse raw schedule schedule data."
  task :parse do
    h = hash_schedule RAW_SCHEDULE
    f = h.first
    p f
  end

  desc "Clean and load raw schedule data into database."
  task :load do
    h = hash_schedule RAW_SCHEDULE
    load_bell_schedules_from h
  end

  desc "Export schedule database to JSON file."
  task :output_json do
    write_schedule_to_json
  end

end